packages:
  - 'packages/*'
  - 'packages/channels/in-app'
  - 'packages/channels/email/*'
  - 'packages/channels/push/*'
  - 'packages/channels/sms/*'
  - 'packages/channels/social-media/whatsapp/*'
  - 'examples/playground'
  - 'examples/expo-townkrier'
