packages:
  - 'packages/*'
  - 'packages/channels/in-app/*'
  - 'packages/channels/email/*'
  - 'packages/channels/push/*'
  - 'packages/channels/sms/*'
  - 'packages/channels/social-media/whatsapp/*'
  - 'examples'
  - 'examples/expo-townkrier'
  # Exclude unstable packages
  - '!packages/cli'
  - '!packages/queue'
  - '!packages/dashboard'
  - '!packages/storage'
