/**
 * Error codes for notification operations
 */
export enum NotificationErrorCode {
  // Configuration errors
  CONFIGURATION_ERROR = 'NOTIFICATION_CONFIGURATION_ERROR',
  INVALID_CONFIG = 'NOTIFICATION_INVALID_CONFIG',
  MISSING_CONFIG = 'NOTIFICATION_MISSING_CONFIG',

  // Channel errors
  CHANNEL_NOT_FOUND = 'NOTIFICATION_CHANNEL_NOT_FOUND',
  CHANNEL_NOT_READY = 'NOTIFICATION_CHANNEL_NOT_READY',
  CHANNEL_ERROR = 'NOTIFICATION_CHANNEL_ERROR',

  // Validation errors
  INVALID_REQUEST = 'NOTIFICATION_INVALID_REQUEST',
  INVALID_RECIPIENT = 'NOTIFICATION_INVALID_RECIPIENT',
  MISSING_REQUIRED_FIELD = 'NOTIFICATION_MISSING_REQUIRED_FIELD',

  // Provider errors
  PROVIDER_ERROR = 'NOTIFICATION_PROVIDER_ERROR',
  PROVIDER_TIMEOUT = 'NOTIFICATION_PROVIDER_TIMEOUT',
  PROVIDER_RATE_LIMIT = 'NOTIFICATION_PROVIDER_RATE_LIMIT',
  INVALID_RESPONSE = 'NOTIFICATION_INVALID_RESPONSE',

  // Send errors
  SEND_FAILED = 'NOTIFICATION_SEND_FAILED',
  DELIVERY_FAILED = 'NOTIFICATION_DELIVERY_FAILED',

  // Unknown errors
  UNKNOWN_ERROR = 'NOTIFICATION_UNKNOWN_ERROR',
}
